const pes = document.createElement("h1");
pes.setAttribute("id", "pes");
//pes.style.position = "absolute";
pes.textContent = "+87";
pes.fontSize = "875%";
pes.style.alignSelf = "center";
pes.style.justifySelf = "center";
//pes.style.positionX = "50%";
//pes.style.positionY = "50%";
document.body.style.backgroundColor = "#000";
document.body.style.color = "#fff";
document.body.style.width = window.screen.availWidth;
document.body.style.height = window.screen.availHeight;
document.body.alignSelf ="center";
document.body.justifySelf = "center";
document.body.alignContent ="center";
document.body.justifyContent = "center";
document.body.alignItems ="center";
document.body.justifyItems = "center";
document.body.appendChild(pes);